create table if not exists public.intake_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  task text,
  success text,
  anything_else text,
  current_process_files jsonb not null default '[]'::jsonb,
  desired_output_files jsonb not null default '[]'::jsonb
);

alter table public.intake_submissions
  add column if not exists status text not null default 'New',
  add column if not exists internal_notes text;

alter table public.intake_submissions
  drop constraint if exists intake_submissions_status_check;

alter table public.intake_submissions
  add constraint intake_submissions_status_check
  check (status in ('New', 'Reviewing', 'Done'));

grant usage on schema public to service_role;
grant select, insert, update on table public.intake_submissions to service_role;
grant usage, select on sequence public.intake_submissions_id_seq to service_role;
